[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django-auditlog-extra"
version = "0.1.0"
authors = [{ name = "City of Helsinki", email = "dev@hel.fi" }]
description = "A module that fixes some issues and provides some reusable tools for Django application using `django-auditlog` in the context of City of Helsinki."
readme = "README.md"
requires-python = ">=3.10"
keywords = [
    "django",
    "auditlog",
    "graphene",
    "rest framework",
    "extra tools",
    "plugin extrension",
]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "django>=5.2",
    "django-auditlog>=3.0.0",
]

[project.urls]
Homepage = "https://github.com/City-of-Helsinki/django-auditlog-extra"
Issues = "https://github.com/City-of-Helsinki/django-auditlog-extra/issues"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-django",
    "coverage",
]
all = ["django-auditlog-extra[test]"]

[tool.coverage.run]
source = ["auditlog_extra"]
omit = ["**/migrations/*"]
relative_files = true
branch = true

[tool.hatch.build.targets.sdist]
include = ["auditlog_extra/*.py"]

[tool.hatch.build.targets.wheel]
packages = ["auditlog_extra"]

[tool.hatch.envs.default]
dependencies = [
    "django~=5.2",
    "pre-commit",
]
features = ["all"]
python = "3.10"

[tool.hatch.envs.default.scripts]
test = "pytest {args}"
lint = [
    "pre-commit install",
    "pre-commit run -a",
]

[tool.hatch.envs.hatch-test]
default-args = ["tests"]
features = ["all"]
matrix-name-format = "dj{value}"
parallel = false
randomize = true

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14"]
django = ["5.2"]

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.12", "3.13", "3.14"]
django = ["6.0"]

[tool.hatch.envs.hatch-test.overrides]
matrix.django.dependencies = [
    { value = "django~={matrix:django}" },
]

[tool.hatch.envs.hatch-test.scripts]
run = [
    "pytest{env:HATCH_TEST_ARGS:} {args}",
]
run-cov = "coverage run -m pytest{env:HATCH_TEST_ARGS:} {args}"
cov-combine = "coverage combine"
cov-report = "coverage report"

[tool.hatch.envs.hatch-uv]
dependencies = [
  "uv>=0.11.1",
]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I",
    # pep8-naming
    "N",
    # flake8-bugbear without opinionated rules
    "B0",
    # flake8-pie
    "PIE",
    # flake8-print
    "T20",
]
extend-per-file-ignores = { "./tests/*" = ["E501"] }

[tool.pytest.ini_options]
pythonpath = "."
DJANGO_SETTINGS_MODULE = "tests.settings"
norecursedirs = [".git", "venv"]

[tool.uv]
exclude-newer = "14 days"
